# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_3knn <- function(X, X0, y) {
    .Call(`_knnpackage_my_3knn`, X, X0, y)
}

my_3knn_invd <- function(X, X0, y) {
    .Call(`_knnpackage_my_3knn_invd`, X, X0, y)
}

my_knn_sourceCpp <- function(X, X0, y) {
    .Call(`_knnpackage_my_knn_sourceCpp`, X, X0, y)
}

rcpp_hello_world <- function() {
    .Call(`_knnpackage_rcpp_hello_world`)
}

